### ISSUE TITLE
[Phcode.dev Bot] Ownership Transferred: Gained ownership of `brackets-disable-toolbar`

### ISSUE THREAD

**Issue by phoenixide** [Rade0nFighter/brackets-disable-toolbar#3]
Greetings from [phcode.dev](https://phcode.dev). You have gained ownership of the extension `brackets-disable-toolbar`. 

Ownership of this extension is now transferred from https://github.com/rade0/brackets-disable-toolbar/ to https://github.com/Rade0nFighter/brackets-disable-toolbar.

**Comment by Rade0nFighter** [comment]
Thanks!
